---

- name: Build HDP3.3
  gather_facts: false
  hosts: all
  become: yes
  tasks:

    - name: Install Java 11 and Jenkins
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
        - java-11-openjdk-devel

- hosts: master
  become: yes
  tasks:
    - name: Create directory on master
      path: /opt/hadoop
      state: directory
      mode: '755'