---

- name: Build HDP3.3
  gather_facts: false

  tasks:
  hosts: all
    - name: Install Java 11 and Jenkins
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
        - java-11-openjdk-devel
      become: yes
      become_user: root