---

- name: Upgrade and add required base packages
  gather_facts: false
  hosts: all
  tasks:

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes
      become_user: root
