---

- name: Build HDP3.3
  gather_facts: false
  hosts: all
  become: yes
  tasks:
  
    - name: Get Hadoop distribution checksum
      get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz.sha512
        dest: /var/tmp/

    - name: Store checksum
      slurp:
        src: /var/tmp/hadoop-3.3.0.tar.gz.sha512
      register: hdp_checksum64

    - debug:
        var: hdp_checksum64

    - name: Get Hadoop distribution
      get_url: 
        url: https://downloads.apache.org/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz
        dest: /var/tmp/
        checksum: "sha512:{{ hdp_checksum }}"
#        checksum: sha512:9ac5a5a8d29de4d2edfb5e554c178b04863375c5644d6fea1f6464ab4a7e22a50a6c43253ea348edbd114fc534dcde5bdd2826007e24b2a6b0ce0d704c5b4f5b
#        checksum: sha512:https://downloads.apache.org/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz.sha512
      vars:
        hdp_checksum: "{{ hdp_checksum64['content'] | b64decode | split(' ')[3] }}"
