---
- name: Test sudo
  hosts: master
  become: yes
  become_user: hadoop
  become method: sudo su -
  tasks:

    - name: Format hdfs
      shell:
        cmd: hdfs namenode -format

    - name: Start hadoop
      shell:
        cmd: start-dfs.sh