---
- name: Test sudo
  hosts: master
  become: yes
  become_user: hadoop
  tasks:

    - name: Update Sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^ansible ALL= (newuser)'
        line: ansible ALL= (newuser) NOPASSWD: ALL