---
- name: Test sudo
  hosts: all
  become: yes
  tasks:

    - name: Open ports for HDFS/MAPRED/HIVE/WEBHCAT (40K-52K)
      firewalld:
        port: 30000-52000/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled