---
- name: Test sudo
  hosts: master
  become: yes
  become_user: hadoop
  tasks:

    - name: Format hdfs
      shell:
        cmd: source /home/hadoop/.bashrc && hdfs namenode -format
      args:
        executable: /bin/bash

    - name: Start hadoop
      shell:
        cmd: source /home/hadoop/.bashrc && start-dfs.sh
      args:
        executable: /bin/bash